version: "3.8"
services:
    nest-server-mpv:
        build: .
        depends_on:
            # Our app does not work without our database
            # so this ensures our database is loaded first
            - nest-db-mvp
            - nest-redis-mvp
        ports:
            - "3000:3000"
        volumes:
            # Maps our current project directory `.` to
            # our working directory in the container
            - ./:/usr/home/app/
            # node_modules workaround for volumes
            # https://stackoverflow.com/a/32785014
            - /usr/home/app/node_modules
        environment:
            - NODE_ENV=production
            - ENVIRONMENT=production
            - PORT=3000
            - DB_NAME=postgres
            - DB_USER=postgres
            - DB_PWD=postgres
            - DB_HOST=nest-db-mvp
            - DB_PORT=5432
            - BCRYPT_ROUNDS=10
            - REDIS_PORT=6379
            - REDIS_DB=1
            - REDIS_HOST=nest-redis-mvp
            - REDIS_PREFIX=vending_machine
        command: ["/bin/bash", "./scripts/entrypoint.sh"]


    nest-db-mvp:
        image: postgres:12-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"


    nest-redis-mvp:
        image: redis:6.2-alpine
        restart: always
        ports:
        - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning 
    
    

